### PR TITLE
feature/icon-theme: First version for vscode icons

### PR DESCRIPTION
**Pull request by coderdiaz**
## Feature
- Add dark icon theme.
- Add light icon theme.

## Test
- Clone the PR branch into `~/.vscode/extensions`.
- Restart Visual Studio Code.
- Shift + Cmd + P for show Command Palette.
- Search `File Icon Theme`.
- Select `City Lights Icon Theme (Visual Studio Code)`.
- Enjoy it :).

### For Light themes

image

### For Dark themes

image

### CODE REVIEW

**Comment by noudadrichem** [comment]
This looks awesome!

Only thing i'm seeing in the light theme is that for example the HTML icon still uses the non active version of the icon. Is that intended? Same counts for travis icon.

**Comment by coderdiaz** [comment]
@noudadrichem Fixed :) 

image

**Comment by noudadrichem** [comment]
Great!

**Comment by coderdiaz** [comment]
@noudadrichem Updated PR info 😁

**Comment by noudadrichem** [comment]
Hi @coderdiaz,

Looks great, well done!

_Question:
Is it possible to create some sort of toggle to also be able to show the colored icons in a dark theme and vise versa?_

**Comment by coderdiaz** [comment]
@noudadrichem Do you mean to show colored icons in dark mode and gray colors to light mode?

**Pull request merged**
